[2024-11-18T22:13:10.983+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-18T22:13:11.007+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_customers_data_to_db.wait_for_dag_load_sales_data_to_db manual__2024-11-18T22:13:07.962120+00:00 [queued]>
[2024-11-18T22:13:11.018+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_customers_data_to_db.wait_for_dag_load_sales_data_to_db manual__2024-11-18T22:13:07.962120+00:00 [queued]>
[2024-11-18T22:13:11.019+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-18T22:13:11.039+0000] {taskinstance.py:2889} INFO - Executing <Task(ExternalTaskSensor): wait_for_dag_load_sales_data_to_db> on 2024-11-18 22:13:07.962120+00:00
[2024-11-18T22:13:11.047+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=291) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-18T22:13:11.049+0000] {standard_task_runner.py:72} INFO - Started process 293 to run task
[2024-11-18T22:13:11.050+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_customers_data_to_db', 'wait_for_dag_load_sales_data_to_db', 'manual__2024-11-18T22:13:07.962120+00:00', '--job-id', '487', '--raw', '--subdir', 'DAGS_FOLDER/refined/insert_data_to_3.py', '--cfg-path', '/tmp/tmpbu5scso5']
[2024-11-18T22:13:11.051+0000] {standard_task_runner.py:105} INFO - Job 487: Subtask wait_for_dag_load_sales_data_to_db
[2024-11-18T22:13:11.111+0000] {task_command.py:467} INFO - Running <TaskInstance: load_customers_data_to_db.wait_for_dag_load_sales_data_to_db manual__2024-11-18T22:13:07.962120+00:00 [running]> on host c06adc74012b
[2024-11-18T22:13:11.220+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_customers_data_to_db' AIRFLOW_CTX_TASK_ID='wait_for_dag_load_sales_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T22:13:07.962120+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T22:13:07.962120+00:00'
[2024-11-18T22:13:11.222+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-18T22:13:11.223+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-18T22:13:11.224+0000] {logging_mixin.py:190} INFO - Current task name:wait_for_dag_load_sales_data_to_db state:running start_date:2024-11-18 22:13:11.008229+00:00
[2024-11-18T22:13:11.224+0000] {logging_mixin.py:190} INFO - Dag name:load_customers_data_to_db and current dag run status:running
[2024-11-18T22:13:11.225+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-18T22:13:11.226+0000] {baseoperator.py:416} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2024-11-18T22:13:11.226+0000] {external_task.py:258} INFO - Poking for tasks ['insert_sales_data'] in dag raw_api_sales_data on 2024-11-18T22:13:07.962120+00:00 ... 
[2024-11-18T22:13:11.228+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/session.py:97: DeprecationWarning: This method is deprecated and will be removed in future.
  return func(*args, session=session, **kwargs)

[2024-11-18T22:13:22.696+0000] {external_task.py:258} INFO - Poking for tasks ['insert_sales_data'] in dag raw_api_sales_data on 2024-11-18T22:13:07.962120+00:00 ... 
[2024-11-18T22:13:22.730+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 348, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 323, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 10.050182409999252 seconds exceeds the specified timeout of 10.0.
[2024-11-18T22:13:22.748+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-18T22:13:22.749+0000] {logging_mixin.py:190} INFO - Task start:2024-11-18 22:13:11.008229+00:00 end:2024-11-18 22:13:22.747653+00:00 duration:11.739424
[2024-11-18T22:13:22.749+0000] {logging_mixin.py:190} INFO - Task:<Task(ExternalTaskSensor): wait_for_dag_load_sales_data_to_db> dag:<DAG: load_customers_data_to_db> dagrun:<DagRun load_customers_data_to_db @ 2024-11-18 22:13:07.962120+00:00: manual__2024-11-18T22:13:07.962120+00:00, state:running, queued_at: 2024-11-18 22:13:07.974165+00:00. externally triggered: True>
[2024-11-18T22:13:22.750+0000] {logging_mixin.py:190} INFO - Failure caused by Sensor has timed out; run duration of 10.050182409999252 seconds exceeds the specified timeout of 10.0.
[2024-11-18T22:13:22.751+0000] {taskinstance.py:1225} INFO - Immediate failure requested. Marking task as FAILED. dag_id=load_customers_data_to_db, task_id=wait_for_dag_load_sales_data_to_db, run_id=manual__2024-11-18T22:13:07.962120+00:00, execution_date=20241118T221307, start_date=20241118T221311, end_date=20241118T221322
[2024-11-18T22:13:22.767+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-18T22:13:22.768+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 487 for task wait_for_dag_load_sales_data_to_db (Sensor has timed out; run duration of 10.050182409999252 seconds exceeds the specified timeout of 10.0.; 293)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 348, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 323, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 10.050182409999252 seconds exceeds the specified timeout of 10.0.
[2024-11-18T22:13:22.785+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-18T22:13:22.813+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-18T22:13:22.818+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
