[2024-11-18T22:20:52.045+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-18T22:20:52.107+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_customers_data_to_db.transform_data manual__2024-11-18T22:20:34.289010+00:00 [queued]>
[2024-11-18T22:20:52.129+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_customers_data_to_db.transform_data manual__2024-11-18T22:20:34.289010+00:00 [queued]>
[2024-11-18T22:20:52.131+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-11-18T22:20:52.170+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform_data> on 2024-11-18 22:20:34.289010+00:00
[2024-11-18T22:20:52.184+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=431) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-18T22:20:52.187+0000] {standard_task_runner.py:72} INFO - Started process 433 to run task
[2024-11-18T22:20:52.188+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_customers_data_to_db', 'transform_data', 'manual__2024-11-18T22:20:34.289010+00:00', '--job-id', '498', '--raw', '--subdir', 'DAGS_FOLDER/refined/insert_data_to_3.py', '--cfg-path', '/tmp/tmppdyx18un']
[2024-11-18T22:20:52.192+0000] {standard_task_runner.py:105} INFO - Job 498: Subtask transform_data
[2024-11-18T22:20:52.333+0000] {task_command.py:467} INFO - Running <TaskInstance: load_customers_data_to_db.transform_data manual__2024-11-18T22:20:34.289010+00:00 [running]> on host c06adc74012b
[2024-11-18T22:20:52.564+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_customers_data_to_db' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T22:20:34.289010+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T22:20:34.289010+00:00'
[2024-11-18T22:20:52.567+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-18T22:20:52.568+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-18T22:20:52.569+0000] {logging_mixin.py:190} INFO - Current task name:transform_data state:running start_date:2024-11-18 22:20:52.108418+00:00
[2024-11-18T22:20:52.570+0000] {logging_mixin.py:190} INFO - Dag name:load_customers_data_to_db and current dag run status:running
[2024-11-18T22:20:52.572+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-18T22:20:52.588+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2024-11-18T22:20:52.615+0000] {insert_data_to_3.py:53} ERROR - Failed to insert data into 3 tables: 'NoneType' object has no attribute 'fetchall'
[2024-11-18T22:20:52.621+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/refined/insert_data_to_3.py", line 31, in transform_data
    results = cursor.execute(query).fetchall()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'fetchall'
[2024-11-18T22:20:52.656+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-18T22:20:52.657+0000] {logging_mixin.py:190} INFO - Task start:2024-11-18 22:20:52.108418+00:00 end:2024-11-18 22:20:52.655107+00:00 duration:0.546689
[2024-11-18T22:20:52.658+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform_data> dag:<DAG: load_customers_data_to_db> dagrun:<DagRun load_customers_data_to_db @ 2024-11-18 22:20:34.289010+00:00: manual__2024-11-18T22:20:34.289010+00:00, state:running, queued_at: 2024-11-18 22:20:34.300133+00:00. externally triggered: True>
[2024-11-18T22:20:52.659+0000] {logging_mixin.py:190} INFO - Failure caused by 'NoneType' object has no attribute 'fetchall'
[2024-11-18T22:20:52.660+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=load_customers_data_to_db, task_id=transform_data, run_id=manual__2024-11-18T22:20:34.289010+00:00, execution_date=20241118T222034, start_date=20241118T222052, end_date=20241118T222052
[2024-11-18T22:20:52.690+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-18T22:20:52.692+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 498 for task transform_data ('NoneType' object has no attribute 'fetchall'; 433)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/refined/insert_data_to_3.py", line 31, in transform_data
    results = cursor.execute(query).fetchall()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'fetchall'
[2024-11-18T22:20:52.729+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-18T22:20:52.779+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-18T22:20:52.786+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
