[2024-11-18T12:45:53.133+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-18T12:45:53.186+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_api_sales_data.test scheduled__2024-11-18T12:30:00+00:00 [queued]>
[2024-11-18T12:45:53.210+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_api_sales_data.test scheduled__2024-11-18T12:30:00+00:00 [queued]>
[2024-11-18T12:45:53.212+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-18T12:45:53.280+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): test> on 2024-11-18 12:30:00+00:00
[2024-11-18T12:45:53.296+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=83) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-18T12:45:53.300+0000] {standard_task_runner.py:72} INFO - Started process 88 to run task
[2024-11-18T12:45:53.301+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'raw_api_sales_data', 'test', 'scheduled__2024-11-18T12:30:00+00:00', '--job-id', '310', '--raw', '--subdir', 'DAGS_FOLDER/fetch_data.py', '--cfg-path', '/tmp/tmp5cvvnig1']
[2024-11-18T12:45:53.305+0000] {standard_task_runner.py:105} INFO - Job 310: Subtask test
[2024-11-18T12:45:53.418+0000] {task_command.py:467} INFO - Running <TaskInstance: raw_api_sales_data.test scheduled__2024-11-18T12:30:00+00:00 [running]> on host c06adc74012b
[2024-11-18T12:45:53.619+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='raw_api_sales_data' AIRFLOW_CTX_TASK_ID='test' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T12:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-18T12:30:00+00:00'
[2024-11-18T12:45:53.623+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-18T12:45:53.624+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-18T12:45:53.625+0000] {logging_mixin.py:190} INFO - Current task name:test state:running start_date:2024-11-18 12:45:53.187277+00:00
[2024-11-18T12:45:53.625+0000] {logging_mixin.py:190} INFO - Dag name:raw_api_sales_data and current dag run status:running
[2024-11-18T12:45:53.626+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-18T12:45:53.647+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2024-11-18T12:45:53.664+0000] {logging_mixin.py:190} INFO - Error: connection to server at "host.docker.internal" (192.168.65.254), port 5432 failed: FATAL:  password authentication failed for user "abde"
[2024-11-18T12:45:53.666+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-18T12:45:53.690+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-18T12:45:53.691+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=raw_api_sales_data, task_id=test, run_id=scheduled__2024-11-18T12:30:00+00:00, execution_date=20241118T123000, start_date=20241118T124553, end_date=20241118T124553
[2024-11-18T12:45:53.712+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-18T12:45:53.713+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-18T12:45:53.714+0000] {logging_mixin.py:190} INFO - Dag name:raw_api_sales_data queued_at:2024-11-18 12:45:22.011923+00:00
[2024-11-18T12:45:53.715+0000] {logging_mixin.py:190} INFO - Task hostname:c06adc74012b operator:PythonOperator
[2024-11-18T12:45:53.765+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-18T12:45:53.818+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-18T12:45:53.822+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
