[2024-11-17T22:59:42.585+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-17T22:59:42.630+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_api_sales_data.insert_sales_data manual__2024-11-17T22:59:28.715847+00:00 [queued]>
[2024-11-17T22:59:42.654+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_api_sales_data.insert_sales_data manual__2024-11-17T22:59:28.715847+00:00 [queued]>
[2024-11-17T22:59:42.656+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-17T22:59:42.706+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): insert_sales_data> on 2024-11-17 22:59:28.715847+00:00
[2024-11-17T22:59:42.726+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=595) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-17T22:59:42.731+0000] {standard_task_runner.py:72} INFO - Started process 597 to run task
[2024-11-17T22:59:42.733+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'raw_api_sales_data', 'insert_sales_data', 'manual__2024-11-17T22:59:28.715847+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/fetch_data.py', '--cfg-path', '/tmp/tmp2c79073v']
[2024-11-17T22:59:42.740+0000] {standard_task_runner.py:105} INFO - Job 138: Subtask insert_sales_data
[2024-11-17T22:59:42.918+0000] {task_command.py:467} INFO - Running <TaskInstance: raw_api_sales_data.insert_sales_data manual__2024-11-17T22:59:28.715847+00:00 [running]> on host 525767e32e17
[2024-11-17T22:59:43.653+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='raw_api_sales_data' AIRFLOW_CTX_TASK_ID='insert_sales_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-17T22:59:28.715847+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-17T22:59:28.715847+00:00'
[2024-11-17T22:59:43.656+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-17T22:59:43.658+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-17T22:59:43.659+0000] {logging_mixin.py:190} INFO - Current task name:insert_sales_data state:running start_date:2024-11-17 22:59:42.632254+00:00
[2024-11-17T22:59:43.660+0000] {logging_mixin.py:190} INFO - Dag name:raw_api_sales_data and current dag run status:running
[2024-11-17T22:59:43.662+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-17T22:59:43.692+0000] {logging_mixin.py:190} INFO - sales_data: [{'customer_id': 240, 'customer_name': 'Bobinette McGilleghole', 'age': 73, 'email': 'bmcgilleghole0@wikimedia.org', 'country': 'China', 'postal_code': nan, 'purchase_id': 1748, 'purchase_quantity': 44, 'purchase_date': '6/26/2021', 'product_id': 2071, 'product_name': 'Cucumber - English', 'quantity': 777, 'total_price': 6169.84, 'price_unit': 437.46}, {'customer_id': 437, 'customer_name': 'Cyndia Dodridge', 'age': 25, 'email': 'cdodridge1@blogger.com', 'country': 'Bolivia', 'postal_code': nan, 'purchase_id': 1915, 'purchase_quantity': 78, 'purchase_date': '12/26/2021', 'product_id': 2028, 'product_name': 'Bread - Pumpernickle, Rounds', 'quantity': 515, 'total_price': 6664.96, 'price_unit': 328.66}, {'customer_id': 167, 'customer_name': 'Zonnya Arckoll', 'age': 76, 'email': 'zarckoll2@salon.com', 'country': 'China', 'postal_code': nan, 'purchase_id': 1131, 'purchase_quantity': 7, 'purchase_date': '5/12/2021', 'product_id': 2001, 'product_name': 'Beans - Fava, Canned', 'quantity': 998, 'total_price': 9877.14, 'price_unit': 698.32}, {'customer_id': 888, 'customer_name': 'Tresa Benoix', 'age': 60, 'email': 'tbenoix3@smh.com.au', 'country': 'China', 'postal_code': nan, 'purchase_id': 1339, 'purchase_quantity': 54, 'purchase_date': '11/12/2021', 'product_id': 2085, 'product_name': 'Marsala - Sperone, Fine, D.o.c.', 'quantity': 330, 'total_price': 7264.07, 'price_unit': 460.88}, {'customer_id': 69, 'customer_name': 'Lenna Yellep', 'age': 68, 'email': 'lyellep4@gravatar.com', 'country': 'Bolivia', 'postal_code': nan, 'purchase_id': 1886, 'purchase_quantity': 42, 'purchase_date': '6/18/2021', 'product_id': 2011, 'product_name': 'Stainless Steel Cleaner Vision', 'quantity': 200, 'total_price': 7467.03, 'price_unit': 968.94}, {'customer_id': 331, 'customer_name': 'Tanny Cloutt', 'age': 65, 'email': 'tcloutt5@stanford.edu', 'country': 'China', 'postal_code': nan, 'purchase_id': 475, 'purchase_quantity': 51, 'purchase_date': '3/18/2021', 'product_id': 2052, 'product_name': 'Chutney Sauce - Mango', 'quantity': 591, 'total_price': 8651.51, 'price_unit': 215.73}, {'customer_id': 542, 'customer_name': 'Langsdon Ogglebie', 'age': 83, 'email': 'logglebie6@goodreads.com', 'country': 'Philippines', 'postal_code': '1808', 'purchase_id': 1651, 'purchase_quantity': 87, 'purchase_date': '1/15/2021', 'product_id': 2044, 'product_name': 'Kiwi', 'quantity': 200, 'total_price': 2783.32, 'price_unit': 331.62}, {'customer_id': 522, 'customer_name': 'Myer Godsal', 'age': 84, 'email': 'mgodsal7@bluehost.com', 'country': 'Philippines', 'postal_code': '8702', 'purchase_id': 1951, 'purchase_quantity': 85, 'purchase_date': '7/6/2021', 'product_id': 2017, 'product_name': 'Beef - Roasted, Cooked', 'quantity': 744, 'total_price': 7964.6, 'price_unit': 811.58}, {'customer_id': 381, 'customer_name': 'Tracy Shelvey', 'age': 83, 'email': 'tshelvey8@jimdo.com', 'country': 'Brazil', 'postal_code': '14470-000', 'purchase_id': 1089, 'purchase_quantity': 1, 'purchase_date': '11/27/2021', 'product_id': 2057, 'product_name': 'Mustard - Individual Pkg', 'quantity': 880, 'total_price': 681.05, 'price_unit': 263.15}, {'customer_id': 283, 'customer_name': 'Dorena Gregorio', 'age': 23, 'email': 'dgregorio9@arstechnica.com', 'country': 'Portugal', 'postal_code': '2705-126', 'purchase_id': 554, 'purchase_quantity': 78, 'purchase_date': '1/11/2021', 'product_id': 2078, 'product_name': 'Lemon Tarts', 'quantity': 269, 'total_price': 8521.27, 'price_unit': 134.57}]
[2024-11-17T22:59:43.699+0000] {logging_mixin.py:190} WARNING - --- Logging error ---
[2024-11-17T22:59:43.701+0000] {logging_mixin.py:190} WARNING - Traceback (most recent call last):
[2024-11-17T22:59:43.703+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
[2024-11-17T22:59:43.705+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
[2024-11-17T22:59:43.707+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
[2024-11-17T22:59:43.708+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
[2024-11-17T22:59:43.710+0000] {logging_mixin.py:190} WARNING - TypeError: not all arguments converted during string formatting
[2024-11-17T22:59:43.711+0000] {logging_mixin.py:190} WARNING - Call stack:
[2024-11-17T22:59:43.743+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2024-11-17T22:59:43.748+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/__main__.py", line 62, in main
    args.func(args)
[2024-11-17T22:59:43.750+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2024-11-17T22:59:43.753+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
[2024-11-17T22:59:43.755+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 61, in wrapper
    providers_configuration_loaded(func)(*args, **kwargs)
[2024-11-17T22:59:43.757+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2024-11-17T22:59:43.759+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 234, in worker
    _run_command_with_daemon_option(
[2024-11-17T22:59:43.762+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 47, in _run_command_with_daemon_option
    run_command_with_daemon_option(*args, **kwargs)
[2024-11-17T22:59:43.765+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/daemon_utils.py", line 86, in run_command_with_daemon_option
    callback()
[2024-11-17T22:59:43.768+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 227, in run_celery_worker
    celery_app.worker_main(options)
[2024-11-17T22:59:43.770+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/app/base.py", line 391, in worker_main
    self.start(argv=argv)
[2024-11-17T22:59:43.772+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/app/base.py", line 371, in start
    celery.main(args=argv, standalone_mode=False)
[2024-11-17T22:59:43.774+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2024-11-17T22:59:43.775+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2024-11-17T22:59:43.777+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2024-11-17T22:59:43.779+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2024-11-17T22:59:43.780+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2024-11-17T22:59:43.781+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/bin/base.py", line 135, in caller
    return f(ctx, *args, **kwargs)
[2024-11-17T22:59:43.782+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2024-11-17T22:59:43.783+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2024-11-17T22:59:43.785+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2024-11-17T22:59:43.786+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2024-11-17T22:59:43.788+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2024-11-17T22:59:43.789+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2024-11-17T22:59:43.790+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2024-11-17T22:59:43.792+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 1046, in __init__
    self._create_worker_process(i)
[2024-11-17T22:59:43.794+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2024-11-17T22:59:43.795+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 1158, in _create_worker_process
    w.start()
[2024-11-17T22:59:43.797+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2024-11-17T22:59:43.798+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2024-11-17T22:59:43.799+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2024-11-17T22:59:43.800+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2024-11-17T22:59:43.801+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2024-11-17T22:59:43.802+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2024-11-17T22:59:43.803+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 292, in __call__
    sys.exit(self.workloop(pid=pid))
[2024-11-17T22:59:43.804+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2024-11-17T22:59:43.805+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/app/trace.py", line 651, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2024-11-17T22:59:43.806+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
[2024-11-17T22:59:43.808+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
[2024-11-17T22:59:43.809+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 139, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2024-11-17T22:59:43.810+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 175, in _execute_in_fork
    args.func(args)
[2024-11-17T22:59:43.811+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2024-11-17T22:59:43.812+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
[2024-11-17T22:59:43.813+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2024-11-17T22:59:43.814+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 254, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2024-11-17T22:59:43.815+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 322, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2024-11-17T22:59:43.816+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
[2024-11-17T22:59:43.817+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2024-11-17T22:59:43.818+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
[2024-11-17T22:59:43.819+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/local_task_job_runner.py", line 171, in _execute
    self.task_runner.start()
[2024-11-17T22:59:43.820+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py", line 55, in start
    self.process = self._start_by_fork()
[2024-11-17T22:59:43.821+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2024-11-17T22:59:43.823+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2024-11-17T22:59:43.824+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
[2024-11-17T22:59:43.825+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2024-11-17T22:59:43.826+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2024-11-17T22:59:43.828+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
[2024-11-17T22:59:43.829+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
[2024-11-17T22:59:43.830+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
[2024-11-17T22:59:43.831+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
[2024-11-17T22:59:43.832+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2024-11-17T22:59:43.833+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
[2024-11-17T22:59:43.834+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
[2024-11-17T22:59:43.835+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
[2024-11-17T22:59:43.836+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
[2024-11-17T22:59:43.838+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
[2024-11-17T22:59:43.839+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
[2024-11-17T22:59:43.841+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
[2024-11-17T22:59:43.842+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
[2024-11-17T22:59:43.844+0000] {logging_mixin.py:190} WARNING -   File "/opt/***/dags/fetch_data.py", line 60, in insert_sales_data
    logging.info("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@Successfully fetched sales data from the API.",sales_data)
[2024-11-17T22:59:43.845+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 2216, in info
    root.info(msg, *args, **kwargs)
[2024-11-17T22:59:43.846+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1539, in info
    self._log(INFO, msg, args, **kwargs)
[2024-11-17T22:59:43.847+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1684, in _log
    self.handle(record)
[2024-11-17T22:59:43.848+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1700, in handle
    self.callHandlers(record)
[2024-11-17T22:59:43.849+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
[2024-11-17T22:59:43.850+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1028, in handle
    self.emit(record)
[2024-11-17T22:59:43.851+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/log/file_task_handler.py", line 274, in emit
    self.handler.emit(record)
[2024-11-17T22:59:43.852+0000] {logging_mixin.py:190} WARNING - Message: '@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@Successfully fetched sales data from the API.'
Arguments: ([{'customer_id': 240, 'customer_name': 'Bobinette McGilleghole', 'age': 73, 'email': 'bmcgilleghole0@wikimedia.org', 'country': 'China', 'postal_code': nan, 'purchase_id': 1748, 'purchase_quantity': 44, 'purchase_date': '6/26/2021', 'product_id': 2071, 'product_name': 'Cucumber - English', 'quantity': 777, 'total_price': 6169.84, 'price_unit': 437.46}, {'customer_id': 437, 'customer_name': 'Cyndia Dodridge', 'age': 25, 'email': 'cdodridge1@blogger.com', 'country': 'Bolivia', 'postal_code': nan, 'purchase_id': 1915, 'purchase_quantity': 78, 'purchase_date': '12/26/2021', 'product_id': 2028, 'product_name': 'Bread - Pumpernickle, Rounds', 'quantity': 515, 'total_price': 6664.96, 'price_unit': 328.66}, {'customer_id': 167, 'customer_name': 'Zonnya Arckoll', 'age': 76, 'email': 'zarckoll2@salon.com', 'country': 'China', 'postal_code': nan, 'purchase_id': 1131, 'purchase_quantity': 7, 'purchase_date': '5/12/2021', 'product_id': 2001, 'product_name': 'Beans - Fava, Canned', 'quantity': 998, 'total_price': 9877.14, 'price_unit': 698.32}, {'customer_id': 888, 'customer_name': 'Tresa Benoix', 'age': 60, 'email': 'tbenoix3@smh.com.au', 'country': 'China', 'postal_code': nan, 'purchase_id': 1339, 'purchase_quantity': 54, 'purchase_date': '11/12/2021', 'product_id': 2085, 'product_name': 'Marsala - Sperone, Fine, D.o.c.', 'quantity': 330, 'total_price': 7264.07, 'price_unit': 460.88}, {'customer_id': 69, 'customer_name': 'Lenna Yellep', 'age': 68, 'email': 'lyellep4@gravatar.com', 'country': 'Bolivia', 'postal_code': nan, 'purchase_id': 1886, 'purchase_quantity': 42, 'purchase_date': '6/18/2021', 'product_id': 2011, 'product_name': 'Stainless Steel Cleaner Vision', 'quantity': 200, 'total_price': 7467.03, 'price_unit': 968.94}, {'customer_id': 331, 'customer_name': 'Tanny Cloutt', 'age': 65, 'email': 'tcloutt5@stanford.edu', 'country': 'China', 'postal_code': nan, 'purchase_id': 475, 'purchase_quantity': 51, 'purchase_date': '3/18/2021', 'product_id': 2052, 'product_name': 'Chutney Sauce - Mango', 'quantity': 591, 'total_price': 8651.51, 'price_unit': 215.73}, {'customer_id': 542, 'customer_name': 'Langsdon Ogglebie', 'age': 83, 'email': 'logglebie6@goodreads.com', 'country': 'Philippines', 'postal_code': '1808', 'purchase_id': 1651, 'purchase_quantity': 87, 'purchase_date': '1/15/2021', 'product_id': 2044, 'product_name': 'Kiwi', 'quantity': 200, 'total_price': 2783.32, 'price_unit': 331.62}, {'customer_id': 522, 'customer_name': 'Myer Godsal', 'age': 84, 'email': 'mgodsal7@bluehost.com', 'country': 'Philippines', 'postal_code': '8702', 'purchase_id': 1951, 'purchase_quantity': 85, 'purchase_date': '7/6/2021', 'product_id': 2017, 'product_name': 'Beef - Roasted, Cooked', 'quantity': 744, 'total_price': 7964.6, 'price_unit': 811.58}, {'customer_id': 381, 'customer_name': 'Tracy Shelvey', 'age': 83, 'email': 'tshelvey8@jimdo.com', 'country': 'Brazil', 'postal_code': '14470-000', 'purchase_id': 1089, 'purchase_quantity': 1, 'purchase_date': '11/27/2021', 'product_id': 2057, 'product_name': 'Mustard - Individual Pkg', 'quantity': 880, 'total_price': 681.05, 'price_unit': 263.15}, {'customer_id': 283, 'customer_name': 'Dorena Gregorio', 'age': 23, 'email': 'dgregorio9@arstechnica.com', 'country': 'Portugal', 'postal_code': '2705-126', 'purchase_id': 554, 'purchase_quantity': 78, 'purchase_date': '1/11/2021', 'product_id': 2078, 'product_name': 'Lemon Tarts', 'quantity': 269, 'total_price': 8521.27, 'price_unit': 134.57}],)
[2024-11-17T22:59:43.871+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2024-11-17T22:59:43.874+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fetch_data.py", line 61, in insert_sales_data
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 181, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-11-17T22:59:43.918+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-17T22:59:43.920+0000] {logging_mixin.py:190} INFO - Task start:2024-11-17 22:59:42.632254+00:00 end:2024-11-17 22:59:43.917283+00:00 duration:1.285029
[2024-11-17T22:59:43.921+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): insert_sales_data> dag:<DAG: raw_api_sales_data> dagrun:<DagRun raw_api_sales_data @ 2024-11-17 22:59:28.715847+00:00: manual__2024-11-17T22:59:28.715847+00:00, state:running, queued_at: 2024-11-17 22:59:28.760536+00:00. externally triggered: True>
[2024-11-17T22:59:43.922+0000] {logging_mixin.py:190} INFO - Failure caused by connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-11-17T22:59:43.923+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=raw_api_sales_data, task_id=insert_sales_data, run_id=manual__2024-11-17T22:59:28.715847+00:00, execution_date=20241117T225928, start_date=20241117T225942, end_date=20241117T225943
[2024-11-17T22:59:44.015+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-17T22:59:44.017+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 138 for task insert_sales_data (connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 597)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fetch_data.py", line 61, in insert_sales_data
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 181, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-11-17T22:59:44.083+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-17T22:59:44.122+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-17T22:59:44.125+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
