[2024-11-18T12:49:21.240+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-18T12:49:21.273+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_api_sales_data.test manual__2024-11-18T12:49:07.136697+00:00 [queued]>
[2024-11-18T12:49:21.288+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_api_sales_data.test manual__2024-11-18T12:49:07.136697+00:00 [queued]>
[2024-11-18T12:49:21.289+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-18T12:49:21.325+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): test> on 2024-11-18 12:49:07.136697+00:00
[2024-11-18T12:49:21.335+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=161) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-18T12:49:21.338+0000] {standard_task_runner.py:72} INFO - Started process 170 to run task
[2024-11-18T12:49:21.338+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'raw_api_sales_data', 'test', 'manual__2024-11-18T12:49:07.136697+00:00', '--job-id', '320', '--raw', '--subdir', 'DAGS_FOLDER/fetch_data.py', '--cfg-path', '/tmp/tmpdyxf_8kg']
[2024-11-18T12:49:21.341+0000] {standard_task_runner.py:105} INFO - Job 320: Subtask test
[2024-11-18T12:49:21.435+0000] {task_command.py:467} INFO - Running <TaskInstance: raw_api_sales_data.test manual__2024-11-18T12:49:07.136697+00:00 [running]> on host c06adc74012b
[2024-11-18T12:49:21.632+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='raw_api_sales_data' AIRFLOW_CTX_TASK_ID='test' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T12:49:07.136697+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T12:49:07.136697+00:00'
[2024-11-18T12:49:21.635+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-18T12:49:21.636+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-18T12:49:21.637+0000] {logging_mixin.py:190} INFO - Current task name:test state:running start_date:2024-11-18 12:49:21.274111+00:00
[2024-11-18T12:49:21.638+0000] {logging_mixin.py:190} INFO - Dag name:raw_api_sales_data and current dag run status:running
[2024-11-18T12:49:21.639+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-18T12:49:21.663+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2024-11-18T12:49:21.686+0000] {logging_mixin.py:190} INFO - Error: connection to server at "host.docker.internal" (192.168.65.254), port 5432 failed: FATAL:  password authentication failed for user "postgres"
[2024-11-18T12:49:21.688+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-18T12:49:21.718+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-18T12:49:21.719+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=raw_api_sales_data, task_id=test, run_id=manual__2024-11-18T12:49:07.136697+00:00, execution_date=20241118T124907, start_date=20241118T124921, end_date=20241118T124921
[2024-11-18T12:49:21.745+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-18T12:49:21.746+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-18T12:49:21.747+0000] {logging_mixin.py:190} INFO - Dag name:raw_api_sales_data queued_at:2024-11-18 12:49:07.182530+00:00
[2024-11-18T12:49:21.748+0000] {logging_mixin.py:190} INFO - Task hostname:c06adc74012b operator:PythonOperator
[2024-11-18T12:49:21.798+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-18T12:49:21.853+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-18T12:49:21.856+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
