[2024-11-17T18:10:23.416+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-17T18:10:23.485+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_api_sales_data.insert_sales_data scheduled__2024-11-17T18:00:00+00:00 [queued]>
[2024-11-17T18:10:23.520+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_api_sales_data.insert_sales_data scheduled__2024-11-17T18:00:00+00:00 [queued]>
[2024-11-17T18:10:23.523+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-11-17T18:10:23.601+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): insert_sales_data> on 2024-11-17 18:00:00+00:00
[2024-11-17T18:10:23.622+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=557) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-17T18:10:23.628+0000] {standard_task_runner.py:72} INFO - Started process 559 to run task
[2024-11-17T18:10:23.630+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'raw_api_sales_data', 'insert_sales_data', 'scheduled__2024-11-17T18:00:00+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/fetch_data.py', '--cfg-path', '/tmp/tmpfdcogblb']
[2024-11-17T18:10:23.637+0000] {standard_task_runner.py:105} INFO - Job 84: Subtask insert_sales_data
[2024-11-17T18:10:24.541+0000] {task_command.py:467} INFO - Running <TaskInstance: raw_api_sales_data.insert_sales_data scheduled__2024-11-17T18:00:00+00:00 [running]> on host 2961e7445d69
[2024-11-17T18:10:24.858+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='raw_api_sales_data' AIRFLOW_CTX_TASK_ID='insert_sales_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-17T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-17T18:00:00+00:00'
[2024-11-17T18:10:24.861+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-17T18:10:24.863+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-17T18:10:24.865+0000] {logging_mixin.py:190} INFO - Current task name:insert_sales_data state:running start_date:2024-11-17 18:10:23.487890+00:00
[2024-11-17T18:10:24.887+0000] {logging_mixin.py:190} INFO - Dag name:raw_api_sales_data and current dag run status:running
[2024-11-17T18:10:24.900+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-17T18:10:24.908+0000] {logging_mixin.py:190} INFO - ti: <TaskInstance: raw_api_sales_data.insert_sales_data scheduled__2024-11-17T18:00:00+00:00 [running]>
[2024-11-17T18:10:24.981+0000] {logging_mixin.py:190} INFO - sales_data: [{'customer_id': 176, 'customer_name': 'Shanie Marrian', 'age': 69, 'email': 'smarrian0@themeforest.net', 'country': 'Libya', 'postal_code': nan, 'purchase_id': 130, 'purchase_quantity': 52, 'purchase_date': '10/6/2021', 'product_id': 2070, 'product_name': 'Nut - Hazelnut, Ground, Natural', 'quantity': 3, 'total_price': 8518.16, 'price_unit': 319.88}, {'customer_id': 269, 'customer_name': 'Nancy Livingston', 'age': 75, 'email': 'nlivingston1@com.com', 'country': 'Indonesia', 'postal_code': nan, 'purchase_id': 718, 'purchase_quantity': 3, 'purchase_date': '10/7/2021', 'product_id': 2018, 'product_name': 'Gelatine Leaves - Envelopes', 'quantity': 795, 'total_price': 1603.14, 'price_unit': 720.59}, {'customer_id': 175, 'customer_name': 'Izaak Pratty', 'age': 75, 'email': 'ipratty2@lulu.com', 'country': 'Philippines', 'postal_code': '4805', 'purchase_id': 120, 'purchase_quantity': 19, 'purchase_date': '12/6/2021', 'product_id': 2062, 'product_name': 'Beef - Tenderloin Tails', 'quantity': 139, 'total_price': 5548.76, 'price_unit': 15.25}, {'customer_id': 141, 'customer_name': 'Jay MacPherson', 'age': 40, 'email': 'jmacpherson3@bandcamp.com', 'country': 'Mexico', 'postal_code': '59762', 'purchase_id': 1261, 'purchase_quantity': 87, 'purchase_date': '12/9/2021', 'product_id': 2058, 'product_name': 'Wine - Jafflin Bourgongone', 'quantity': 570, 'total_price': 7129.03, 'price_unit': 123.62}, {'customer_id': 102, 'customer_name': 'Warner Skate', 'age': 54, 'email': 'wskate4@buzzfeed.com', 'country': 'Netherlands', 'postal_code': '7409', 'purchase_id': 1211, 'purchase_quantity': 68, 'purchase_date': '6/5/2021', 'product_id': 2031, 'product_name': 'Bread - Pullman, Sliced', 'quantity': 416, 'total_price': 7033.99, 'price_unit': 786.89}, {'customer_id': 365, 'customer_name': 'Ferne Elkington', 'age': 40, 'email': 'felkington5@typepad.com', 'country': 'Portugal', 'postal_code': '4650-752', 'purchase_id': 1499, 'purchase_quantity': 90, 'purchase_date': '2/13/2021', 'product_id': 2084, 'product_name': 'Bread - Hot Dog Buns', 'quantity': 449, 'total_price': 5203.56, 'price_unit': 396.13}, {'customer_id': 906, 'customer_name': 'Louise Edmead', 'age': 64, 'email': 'ledmead6@myspace.com', 'country': 'China', 'postal_code': nan, 'purchase_id': 333, 'purchase_quantity': 35, 'purchase_date': '12/26/2021', 'product_id': 2002, 'product_name': 'Tomatoes - Heirloom', 'quantity': 174, 'total_price': 7085.37, 'price_unit': 363.41}, {'customer_id': 584, 'customer_name': 'Cori Amer', 'age': 61, 'email': 'camer7@biblegateway.com', 'country': 'Sweden', 'postal_code': '455 31', 'purchase_id': 306, 'purchase_quantity': 45, 'purchase_date': '4/10/2021', 'product_id': 2009, 'product_name': 'Port - 74 Brights', 'quantity': 757, 'total_price': 6406.62, 'price_unit': 279.66}, {'customer_id': 980, 'customer_name': 'Melany Calver', 'age': 45, 'email': 'mcalver8@csmonitor.com', 'country': 'Russia', 'postal_code': '368044', 'purchase_id': 1170, 'purchase_quantity': 26, 'purchase_date': '6/22/2021', 'product_id': 2027, 'product_name': 'Pasta - Cheese / Spinach Bauletti', 'quantity': 808, 'total_price': 7030.61, 'price_unit': 401.01}, {'customer_id': 435, 'customer_name': 'Katrine Jennery', 'age': 70, 'email': 'kjennery9@linkedin.com', 'country': 'Sweden', 'postal_code': '795 92', 'purchase_id': 1972, 'purchase_quantity': 7, 'purchase_date': '7/11/2021', 'product_id': 2064, 'product_name': 'Icecream Cone - Areo Chocolate', 'quantity': 187, 'total_price': 7062.54, 'price_unit': 366.45}]
[2024-11-17T18:10:24.985+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fetch_data.py", line 67, in insert_sales_data
    conn = get_db_connection()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fetch_data.py", line 31, in get_db_connection
    return psycopg2.connect(**DB_PARAMS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-11-17T18:10:25.054+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-17T18:10:25.056+0000] {logging_mixin.py:190} INFO - Task start:2024-11-17 18:10:23.487890+00:00 end:2024-11-17 18:10:25.052476+00:00 duration:1.564586
[2024-11-17T18:10:25.061+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): insert_sales_data> dag:<DAG: raw_api_sales_data> dagrun:<DagRun raw_api_sales_data @ 2024-11-17 18:00:00+00:00: scheduled__2024-11-17T18:00:00+00:00, state:running, queued_at: 2024-11-17 18:10:00.284009+00:00. externally triggered: False>
[2024-11-17T18:10:25.063+0000] {logging_mixin.py:190} INFO - Failure caused by connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-11-17T18:10:25.065+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=raw_api_sales_data, task_id=insert_sales_data, run_id=scheduled__2024-11-17T18:00:00+00:00, execution_date=20241117T180000, start_date=20241117T181023, end_date=20241117T181025
[2024-11-17T18:10:25.130+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-17T18:10:25.132+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 84 for task insert_sales_data (connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 559)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fetch_data.py", line 67, in insert_sales_data
    conn = get_db_connection()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fetch_data.py", line 31, in get_db_connection
    return psycopg2.connect(**DB_PARAMS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-11-17T18:10:25.224+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-17T18:10:25.708+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-17T18:10:25.723+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
