[2024-11-17T22:40:58.416+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-17T22:40:58.716+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_api_sales_data.insert_sales_data scheduled__2024-11-17T22:10:00+00:00 [queued]>
[2024-11-17T22:40:58.744+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_api_sales_data.insert_sales_data scheduled__2024-11-17T22:10:00+00:00 [queued]>
[2024-11-17T22:40:58.745+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-11-17T22:40:58.805+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): insert_sales_data> on 2024-11-17 22:10:00+00:00
[2024-11-17T22:40:58.821+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=336) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-17T22:40:58.825+0000] {standard_task_runner.py:72} INFO - Started process 340 to run task
[2024-11-17T22:40:58.828+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'raw_api_sales_data', 'insert_sales_data', 'scheduled__2024-11-17T22:10:00+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/fetch_data.py', '--cfg-path', '/tmp/tmpj6f7xh7z']
[2024-11-17T22:40:58.832+0000] {standard_task_runner.py:105} INFO - Job 126: Subtask insert_sales_data
[2024-11-17T22:40:59.006+0000] {task_command.py:467} INFO - Running <TaskInstance: raw_api_sales_data.insert_sales_data scheduled__2024-11-17T22:10:00+00:00 [running]> on host 525767e32e17
[2024-11-17T22:40:59.341+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='raw_api_sales_data' AIRFLOW_CTX_TASK_ID='insert_sales_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-17T22:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-17T22:10:00+00:00'
[2024-11-17T22:40:59.345+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-17T22:40:59.346+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-17T22:40:59.348+0000] {logging_mixin.py:190} INFO - Current task name:insert_sales_data state:running start_date:2024-11-17 22:40:58.718103+00:00
[2024-11-17T22:40:59.349+0000] {logging_mixin.py:190} INFO - Dag name:raw_api_sales_data and current dag run status:running
[2024-11-17T22:40:59.350+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-17T22:40:59.353+0000] {logging_mixin.py:190} INFO - ti: <TaskInstance: raw_api_sales_data.insert_sales_data scheduled__2024-11-17T22:10:00+00:00 [running]>
[2024-11-17T22:40:59.381+0000] {logging_mixin.py:190} INFO - sales_data: [{'customer_id': 526, 'customer_name': 'Zoe Glowacki', 'age': 73, 'email': 'zglowacki0@amazon.co.jp', 'country': 'Japan', 'postal_code': '692-0212', 'purchase_id': 436, 'purchase_quantity': 41, 'purchase_date': '12/15/2021', 'product_id': 2010, 'product_name': 'Pork - Tenderloin, Fresh', 'quantity': 336, 'total_price': 5486.49, 'price_unit': 214.35}, {'customer_id': 864, 'customer_name': 'Francine Dufton', 'age': 59, 'email': 'fdufton1@opensource.org', 'country': 'Chile', 'postal_code': nan, 'purchase_id': 1564, 'purchase_quantity': 15, 'purchase_date': '8/30/2021', 'product_id': 2048, 'product_name': 'Tart - Pecan Butter Squares', 'quantity': 714, 'total_price': 3131.13, 'price_unit': 30.73}, {'customer_id': 919, 'customer_name': 'Curcio Cakebread', 'age': 61, 'email': 'ccakebread2@bloomberg.com', 'country': 'South Korea', 'postal_code': nan, 'purchase_id': 1382, 'purchase_quantity': 68, 'purchase_date': '8/21/2021', 'product_id': 2061, 'product_name': 'Pimento - Canned', 'quantity': 905, 'total_price': 7126.9, 'price_unit': 74.66}, {'customer_id': 299, 'customer_name': 'Gerald Langhor', 'age': 68, 'email': 'glanghor3@businessinsider.com', 'country': 'Sweden', 'postal_code': '833 24', 'purchase_id': 1773, 'purchase_quantity': 100, 'purchase_date': '12/10/2021', 'product_id': 2069, 'product_name': 'Pepper - Black, Ground', 'quantity': 136, 'total_price': 6433.33, 'price_unit': 829.06}, {'customer_id': 702, 'customer_name': 'Hermine Lavies', 'age': 40, 'email': 'hlavies4@blogspot.com', 'country': 'Azerbaijan', 'postal_code': nan, 'purchase_id': 1617, 'purchase_quantity': 27, 'purchase_date': '9/9/2021', 'product_id': 2041, 'product_name': 'Loquat', 'quantity': 379, 'total_price': 1392.98, 'price_unit': 11.1}, {'customer_id': 28, 'customer_name': 'Magdalena Brimmicombe', 'age': 27, 'email': 'mbrimmicombe5@blogtalkradio.com', 'country': 'Nigeria', 'postal_code': nan, 'purchase_id': 1525, 'purchase_quantity': 66, 'purchase_date': '10/21/2021', 'product_id': 2030, 'product_name': 'Coconut - Shredded, Sweet', 'quantity': 695, 'total_price': 544.14, 'price_unit': 844.93}, {'customer_id': 991, 'customer_name': 'Tally McBayne', 'age': 46, 'email': 'tmcbayne6@wunderground.com', 'country': 'Poland', 'postal_code': '55-120', 'purchase_id': 1718, 'purchase_quantity': 21, 'purchase_date': '11/30/2021', 'product_id': 2025, 'product_name': 'Beer - Tetleys', 'quantity': 976, 'total_price': 3105.53, 'price_unit': 644.73}, {'customer_id': 274, 'customer_name': 'Marci Eagland', 'age': 27, 'email': 'meagland7@mysql.com', 'country': 'Iraq', 'postal_code': nan, 'purchase_id': 326, 'purchase_quantity': 24, 'purchase_date': '6/9/2021', 'product_id': 2020, 'product_name': 'Turnip - White, Organic', 'quantity': 669, 'total_price': 5457.82, 'price_unit': 864.16}, {'customer_id': 660, 'customer_name': 'Miner Wheway', 'age': 82, 'email': 'mwheway8@google.com', 'country': 'Brazil', 'postal_code': '14160-000', 'purchase_id': 455, 'purchase_quantity': 57, 'purchase_date': '1/16/2021', 'product_id': 2096, 'product_name': 'Cheese - Le Cheve Noir', 'quantity': 743, 'total_price': 8349.12, 'price_unit': 735.27}, {'customer_id': 322, 'customer_name': 'Neil Belvard', 'age': 39, 'email': 'nbelvard9@e-recht24.de', 'country': 'Sweden', 'postal_code': '852 36', 'purchase_id': 1809, 'purchase_quantity': 40, 'purchase_date': '8/15/2021', 'product_id': 2003, 'product_name': 'Muffin Batt - Blueberry Passion', 'quantity': 246, 'total_price': 2372.82, 'price_unit': 888.35}]
[2024-11-17T22:40:59.407+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2024-11-17T22:40:59.414+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fetch_data.py", line 59, in insert_sales_data
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 181, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-11-17T22:40:59.444+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-17T22:40:59.445+0000] {logging_mixin.py:190} INFO - Task start:2024-11-17 22:40:58.718103+00:00 end:2024-11-17 22:40:59.443777+00:00 duration:0.725674
[2024-11-17T22:40:59.447+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): insert_sales_data> dag:<DAG: raw_api_sales_data> dagrun:<DagRun raw_api_sales_data @ 2024-11-17 22:10:00+00:00: scheduled__2024-11-17T22:10:00+00:00, state:running, queued_at: 2024-11-17 22:40:21.137509+00:00. externally triggered: False>
[2024-11-17T22:40:59.448+0000] {logging_mixin.py:190} INFO - Failure caused by connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-11-17T22:40:59.449+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=raw_api_sales_data, task_id=insert_sales_data, run_id=scheduled__2024-11-17T22:10:00+00:00, execution_date=20241117T221000, start_date=20241117T224058, end_date=20241117T224059
[2024-11-17T22:40:59.484+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-17T22:40:59.485+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 126 for task insert_sales_data (connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 340)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fetch_data.py", line 59, in insert_sales_data
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 181, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-11-17T22:40:59.573+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-17T22:40:59.614+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
