[2024-11-17T22:06:19.368+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-17T22:06:19.588+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_api_sales_data.insert_sales_data manual__2024-11-17T22:06:07.318775+00:00 [queued]>
[2024-11-17T22:06:19.603+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_api_sales_data.insert_sales_data manual__2024-11-17T22:06:07.318775+00:00 [queued]>
[2024-11-17T22:06:19.604+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-17T22:06:19.634+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): insert_sales_data> on 2024-11-17 22:06:07.318775+00:00
[2024-11-17T22:06:19.646+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=171) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-17T22:06:19.649+0000] {standard_task_runner.py:72} INFO - Started process 173 to run task
[2024-11-17T22:06:19.651+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'raw_api_sales_data', 'insert_sales_data', 'manual__2024-11-17T22:06:07.318775+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/fetch_data.py', '--cfg-path', '/tmp/tmp6rpih3du']
[2024-11-17T22:06:19.654+0000] {standard_task_runner.py:105} INFO - Job 113: Subtask insert_sales_data
[2024-11-17T22:06:19.746+0000] {task_command.py:467} INFO - Running <TaskInstance: raw_api_sales_data.insert_sales_data manual__2024-11-17T22:06:07.318775+00:00 [running]> on host 525767e32e17
[2024-11-17T22:06:19.912+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='raw_api_sales_data' AIRFLOW_CTX_TASK_ID='insert_sales_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-17T22:06:07.318775+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-17T22:06:07.318775+00:00'
[2024-11-17T22:06:19.915+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-17T22:06:19.916+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-17T22:06:19.917+0000] {logging_mixin.py:190} INFO - Current task name:insert_sales_data state:running start_date:2024-11-17 22:06:19.589272+00:00
[2024-11-17T22:06:19.918+0000] {logging_mixin.py:190} INFO - Dag name:raw_api_sales_data and current dag run status:running
[2024-11-17T22:06:19.918+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-17T22:06:19.920+0000] {logging_mixin.py:190} INFO - ti: <TaskInstance: raw_api_sales_data.insert_sales_data manual__2024-11-17T22:06:07.318775+00:00 [running]>
[2024-11-17T22:06:19.936+0000] {logging_mixin.py:190} INFO - sales_data: [{'customer_id': 508, 'customer_name': 'Tandi Cunnah', 'age': 47, 'email': 'tcunnah0@lycos.com', 'country': 'Bangladesh', 'postal_code': '1510', 'purchase_id': 516, 'purchase_quantity': 75, 'purchase_date': '7/12/2021', 'product_id': 2086, 'product_name': 'Pepper - Chillies, Crushed', 'quantity': 17, 'total_price': 9914.19, 'price_unit': 736.47}, {'customer_id': 342, 'customer_name': 'Thatcher Larchiere', 'age': 74, 'email': 'tlarchiere1@hud.gov', 'country': 'Brazil', 'postal_code': '83200-000', 'purchase_id': 935, 'purchase_quantity': 44, 'purchase_date': '7/1/2021', 'product_id': 2087, 'product_name': 'Wine - Dubouef Macon - Villages', 'quantity': 42, 'total_price': 3670.66, 'price_unit': 554.89}, {'customer_id': 646, 'customer_name': 'Tamiko Colleran', 'age': 37, 'email': 'tcolleran2@google.ru', 'country': 'Mexico', 'postal_code': '48324', 'purchase_id': 1606, 'purchase_quantity': 66, 'purchase_date': '6/12/2021', 'product_id': 2075, 'product_name': 'Nacho Chips', 'quantity': 343, 'total_price': 7586.15, 'price_unit': 176.03}, {'customer_id': 424, 'customer_name': 'Leesa Bilton', 'age': 82, 'email': 'lbilton3@cnbc.com', 'country': 'China', 'postal_code': nan, 'purchase_id': 1421, 'purchase_quantity': 33, 'purchase_date': '9/10/2021', 'product_id': 2038, 'product_name': 'Puree - Mango', 'quantity': 16, 'total_price': 1626.42, 'price_unit': 565.96}, {'customer_id': 142, 'customer_name': 'Raleigh Wakenshaw', 'age': 34, 'email': 'rwakenshaw4@storify.com', 'country': 'Norway', 'postal_code': '0773', 'purchase_id': 1644, 'purchase_quantity': 54, 'purchase_date': '9/9/2021', 'product_id': 2025, 'product_name': 'Coffee - Beans, Whole', 'quantity': 437, 'total_price': 6128.63, 'price_unit': 35.33}, {'customer_id': 248, 'customer_name': 'Diarmid Beasant', 'age': 71, 'email': 'dbeasant5@prnewswire.com', 'country': 'Portugal', 'postal_code': '5030-213', 'purchase_id': 1297, 'purchase_quantity': 39, 'purchase_date': '10/7/2021', 'product_id': 2029, 'product_name': 'Icecream - Dstk Cml And Fdg', 'quantity': 934, 'total_price': 8162.68, 'price_unit': 448.62}, {'customer_id': 91, 'customer_name': 'Christi Rudledge', 'age': 47, 'email': 'crudledge6@digg.com', 'country': 'Portugal', 'postal_code': '3305-096', 'purchase_id': 1084, 'purchase_quantity': 18, 'purchase_date': '1/24/2021', 'product_id': 2072, 'product_name': 'Tea - Herbal Orange Spice', 'quantity': 745, 'total_price': 8989.15, 'price_unit': 672.95}, {'customer_id': 188, 'customer_name': 'Yorker Uzzell', 'age': 20, 'email': 'yuzzell7@ehow.com', 'country': 'Iran', 'postal_code': nan, 'purchase_id': 1589, 'purchase_quantity': 35, 'purchase_date': '11/2/2021', 'product_id': 2042, 'product_name': 'General Purpose Trigger', 'quantity': 725, 'total_price': 5836.18, 'price_unit': 693.01}, {'customer_id': 946, 'customer_name': 'Vere Spratling', 'age': 42, 'email': 'vspratling8@java.com', 'country': 'France', 'postal_code': '55013 CEDEX', 'purchase_id': 1640, 'purchase_quantity': 28, 'purchase_date': '12/5/2021', 'product_id': 2039, 'product_name': 'Cassis', 'quantity': 799, 'total_price': 7280.51, 'price_unit': 655.34}, {'customer_id': 652, 'customer_name': 'Jarred Kilgallen', 'age': 53, 'email': 'jkilgallen9@cafepress.com', 'country': 'Russia', 'postal_code': '359050', 'purchase_id': 983, 'purchase_quantity': 96, 'purchase_date': '10/28/2021', 'product_id': 2057, 'product_name': 'Sauce - Alfredo', 'quantity': 838, 'total_price': 7427.7, 'price_unit': 311.5}]
[2024-11-17T22:06:19.953+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2024-11-17T22:06:19.955+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fetch_data.py", line 59, in insert_sales_data
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 181, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-11-17T22:06:19.986+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-17T22:06:19.987+0000] {logging_mixin.py:190} INFO - Task start:2024-11-17 22:06:19.589272+00:00 end:2024-11-17 22:06:19.985438+00:00 duration:0.396166
[2024-11-17T22:06:19.988+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): insert_sales_data> dag:<DAG: raw_api_sales_data> dagrun:<DagRun raw_api_sales_data @ 2024-11-17 22:06:07.318775+00:00: manual__2024-11-17T22:06:07.318775+00:00, state:running, queued_at: 2024-11-17 22:06:07.361911+00:00. externally triggered: True>
[2024-11-17T22:06:19.989+0000] {logging_mixin.py:190} INFO - Failure caused by connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-11-17T22:06:19.990+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=raw_api_sales_data, task_id=insert_sales_data, run_id=manual__2024-11-17T22:06:07.318775+00:00, execution_date=20241117T220607, start_date=20241117T220619, end_date=20241117T220619
[2024-11-17T22:06:20.020+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-17T22:06:20.022+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 113 for task insert_sales_data (connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 173)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fetch_data.py", line 59, in insert_sales_data
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 181, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-11-17T22:06:20.067+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-17T22:06:20.113+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-17T22:06:20.116+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
